namespace RipCheck
{
    enum GuitarTrackNote : byte
    {
        // Does not include CH's tap note marker or note-based open notes
        // Inverse order for easier referencing of charts in a piano-roll view
        TrillLane = 127,
        StrumLane = 126,
        BRE1 = 124,
        BRE2 = 123,
        BRE3 = 122,
        BRE4 = 121,
        BRE5 = 120,
        Overdrive = 116,
        GH1BigNote = 110,
        GH1VocalistMouth = 108,
        ScoreDuelPlayer2 = 106,
        ScoreDuelPlayer1 = 105,
        Solo = 103,

        ExpertGHFaceOff2 = 106,
        ExpertGHFaceOff1 = 105,
        ExpertGHStarPower = 103,
        ExpertForceStrum = 102,
        ExpertForceHOPO = 101,
        ExpertOrange = 100,
        ExpertBlue = 99,
        ExpertYellow = 98,
        ExpertRed = 97,
        ExpertGreen = 96,

        HardGHFaceOff2 = 94,
        HardGHFaceOff1 = 93,
        HardGHStarPower = 91,
        HardForceStrum = 90,
        HardForceHOPO = 89,
        HardOrange = 88,
        HardBlue = 87,
        HardYellow = 86,
        HardRed = 85,
        HardGreen = 84,

        MediumGHFaceOff2 = 82,
        MediumGHFaceOff1 = 81,
        MediumGHStarPower = 79,
        MediumForceStrum = 78,
        MediumForceHOPO = 77,
        MediumOrange = 76,
        MediumBlue = 75,
        MediumYellow = 74,
        MediumRed = 73,
        MediumGreen = 72,

        EasyGHFaceOff2 = 70,
        EasyGHFaceOff1 = 69,
        EasyGHStarPower = 67,
        EasyForceStrum = 66,
        EasyForceHOPO = 65,
        EasyOrange = 64,
        EasyBlue = 63,
        EasyYellow = 62,
        EasyRed = 61,
        EasyGreen = 60,

        LeftHand20 = 59,
        LeftHand19 = 58,
        LeftHand18 = 57,
        LeftHand17 = 56,
        LeftHand16 = 55,
        LeftHand15 = 54,
        LeftHand14 = 53,
        LeftHand13 = 52,
        LeftHand12 = 51,
        LeftHand11 = 50,
        LeftHand10 = 49,
        LeftHand9 = 48,
        LeftHand8 = 47,
        LeftHand7 = 46,
        LeftHand6 = 45,
        LeftHand5 = 44,
        LeftHand4 = 43,
        LeftHand3 = 42,
        LeftHand2 = 41,
        LeftHand1 = 40,
    }
}