namespace RipCheck
{
    enum ProGuitarTrackNote : byte
    {
        // Inverse order for easier referencing of charts in a piano-roll view
        TrillLane = 127,
        StrumLane = 126,
        BRE1 = 125,
        BRE2 = 124,
        BRE3 = 123,
        BRE4 = 122,
        BRE5 = 121,
        BRE6 = 120,
        Overdrive = 116,
        Solo = 115,
        PlayerHandPosition = 108,
        ForceChordNumbering = 107,

        ExpertStringEmphasis = 105,
        ExpertArpeggio = 104,
        ExpertSlide = 103,
        ExpertForceHOPO = 102,
        ExpertPurple = 101,
        ExpertYellow = 100,
        ExpertBlue = 99,
        ExpertOrange = 98,
        ExpertGreen = 97,
        ExpertRed = 96,

        HardStringEmphasis = 81,
        HardArpeggio = 80,
        HardSlide = 79,
        HardForceHOPO = 78,
        HardPurple = 77,
        HardYellow = 76,
        HardBlue = 75,
        HardOrange = 74,
        HardGreen = 73,
        HardRed = 72,

        MediumStringEmphasis = 57,
        MediumArpeggio = 56,
        MediumSlide = 55,
        MediumForceHOPO = 54,
        MediumPurple = 53,
        MediumYellow = 52,
        MediumBlue = 51,
        MediumOrange = 50,
        MediumGreen = 49,
        MediumRed = 48,

        EasyStringEmphasis = 33,
        EasyArpeggio = 32,
        EasySlide = 31,
        EasyForceHOPO = 30,
        EasyPurple = 29,
        EasyYellow = 28,
        EasyBlue = 27,
        EasyOrange = 26,
        EasyGreen = 25,
        EasyRed = 24,

        SharpFlatSwap = 18,
        HideChordName = 17,
        SlashChord = 16,
        RootNoteEb = 15,
        RootNoteD = 14,
        RootNoteDb = 13,
        RootNoteC = 12,
        RootNoteB = 11,
        RootNoteBb = 10,
        RootNoteA = 9,
        RootNoteAb = 8,
        RootNoteG = 7,
        RootNoteGb = 6,
        RootNoteF = 5,
        RootNoteE = 4
    }
    
    enum ProGuitarTrackChannel : byte
    {
        Normal = 0,
        Ghost = 1,
        ArpeggioChordShape = 1,
        Bend = 2,
        Muted = 3,
        Tapped = 4,
        Harmonics = 5,
        PinchHarmonics = 6,
        SlideDirectionSwap = 11,
        StringEmphasisEAD = 13,
        StringEmphasisDGB = 14,
        BassSlap = 14,
        StringEmphasisGBe = 15,
    }
}